In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:

python_list=list(range(100))

In [6]:
python_list[0:5]

[0, 1, 2, 3, 4]

In [10]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

2400

In [15]:
import numpy as np
numpy_array = np.arange(100)
print(numpy_array[:5])

[0 1 2 3 4]


In [16]:
import time
size=100000
l1=list(range(size))
l2=list(range(size))
l3=(x+y for x,y in zip(l1,l2))

In [31]:
import numpy as np
n1=np.arange(5)
n2=np.arange(5)
n1,n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [32]:
n1*n2

array([ 0,  1,  4,  9, 16])

In [33]:
rev_q1=np.array([10,12,13])
rev_q1.ndim

1